/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRouteRouteImport } from './routes/cliente/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DiagnosticoIndexRouteImport } from './routes/diagnostico/index'
import { Route as MediaIndoorIndexRouteImport } from './routes/media-indoor/index'
import { Route as MembrosIndexRouteImport } from './routes/membros/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SitesTemplateSlugRouteImport } from './routes/sites/$templateSlug'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes/index'
import { Route as SolucoesProductSlugRouteImport } from './routes/solucoes/$productSlug'
import { Route as AdminSitesIndexRouteImport } from './routes/admin/sites/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ClienteSitesIndexRouteImport } from './routes/cliente/sites/index'
import { Route as SitesTemplateSlugPedidoRouteImport } from './routes/sites/$templateSlug/pedido'
import { Route as SitesAprovacaoTokenRouteImport } from './routes/sites/aprovacao/$token'
import { Route as ClienteSitesPagamentoOrderIdRouteImport } from './routes/cliente/sites/pagamento/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRouteRoute = ClienteRouteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoIndexRoute = DiagnosticoIndexRouteImport.update({
  id: '/diagnostico/',
  path: '/diagnostico/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndoorIndexRoute = MediaIndoorIndexRouteImport.update({
  id: '/media-indoor/',
  path: '/media-indoor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosIndexRoute = MembrosIndexRouteImport.update({
  id: '/membros/',
  path: '/membros/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesTemplateSlugRoute = SitesTemplateSlugRouteImport.update({
  id: '/sites/$templateSlug',
  path: '/sites/$templateSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesProductSlugRoute = SolucoesProductSlugRouteImport.update({
  id: '/solucoes/$productSlug',
  path: '/solucoes/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesIndexRoute = AdminSitesIndexRouteImport.update({
  id: '/admin/sites/',
  path: '/admin/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteSitesIndexRoute = ClienteSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const SitesTemplateSlugPedidoRoute = SitesTemplateSlugPedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => SitesTemplateSlugRoute,
} as any)
const SitesAprovacaoTokenRoute = SitesAprovacaoTokenRouteImport.update({
  id: '/sites/aprovacao/$token',
  path: '/sites/aprovacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteSitesPagamentoOrderIdRoute =
  ClienteSitesPagamentoOrderIdRouteImport.update({
    id: '/sites/pagamento/$orderId',
    path: '/sites/pagamento/$orderId',
    getParentRoute: () => ClienteRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/parceiros': typeof ParceirosRoute
  '/sites/$templateSlug': typeof SitesTemplateSlugRouteWithChildren
  '/solucoes/$productSlug': typeof SolucoesProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/media-indoor/': typeof MediaIndoorIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/sites/$templateSlug/pedido': typeof SitesTemplateSlugPedidoRoute
  '/sites/aprovacao/$token': typeof SitesAprovacaoTokenRoute
  '/admin/sites/': typeof AdminSitesIndexRoute
  '/cliente/sites/': typeof ClienteSitesIndexRoute
  '/cliente/sites/pagamento/$orderId': typeof ClienteSitesPagamentoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/parceiros': typeof ParceirosRoute
  '/sites/$templateSlug': typeof SitesTemplateSlugRouteWithChildren
  '/solucoes/$productSlug': typeof SolucoesProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/diagnostico': typeof DiagnosticoIndexRoute
  '/media-indoor': typeof MediaIndoorIndexRoute
  '/membros': typeof MembrosIndexRoute
  '/sites': typeof SitesIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/sites/$templateSlug/pedido': typeof SitesTemplateSlugPedidoRoute
  '/sites/aprovacao/$token': typeof SitesAprovacaoTokenRoute
  '/admin/sites': typeof AdminSitesIndexRoute
  '/cliente/sites': typeof ClienteSitesIndexRoute
  '/cliente/sites/pagamento/$orderId': typeof ClienteSitesPagamentoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/parceiros': typeof ParceirosRoute
  '/sites/$templateSlug': typeof SitesTemplateSlugRouteWithChildren
  '/solucoes/$productSlug': typeof SolucoesProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/media-indoor/': typeof MediaIndoorIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/sites/$templateSlug/pedido': typeof SitesTemplateSlugPedidoRoute
  '/sites/aprovacao/$token': typeof SitesAprovacaoTokenRoute
  '/admin/sites/': typeof AdminSitesIndexRoute
  '/cliente/sites/': typeof ClienteSitesIndexRoute
  '/cliente/sites/pagamento/$orderId': typeof ClienteSitesPagamentoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/login'
    | '/parceiros'
    | '/sites/$templateSlug'
    | '/solucoes/$productSlug'
    | '/admin/'
    | '/diagnostico/'
    | '/media-indoor/'
    | '/membros/'
    | '/sites/'
    | '/solucoes/'
    | '/api/public/health'
    | '/sites/$templateSlug/pedido'
    | '/sites/aprovacao/$token'
    | '/admin/sites/'
    | '/cliente/sites/'
    | '/cliente/sites/pagamento/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/login'
    | '/parceiros'
    | '/sites/$templateSlug'
    | '/solucoes/$productSlug'
    | '/admin'
    | '/diagnostico'
    | '/media-indoor'
    | '/membros'
    | '/sites'
    | '/solucoes'
    | '/api/public/health'
    | '/sites/$templateSlug/pedido'
    | '/sites/aprovacao/$token'
    | '/admin/sites'
    | '/cliente/sites'
    | '/cliente/sites/pagamento/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/login'
    | '/parceiros'
    | '/sites/$templateSlug'
    | '/solucoes/$productSlug'
    | '/admin/'
    | '/diagnostico/'
    | '/media-indoor/'
    | '/membros/'
    | '/sites/'
    | '/solucoes/'
    | '/api/public/health'
    | '/sites/$templateSlug/pedido'
    | '/sites/aprovacao/$token'
    | '/admin/sites/'
    | '/cliente/sites/'
    | '/cliente/sites/pagamento/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRouteRoute: typeof ClienteRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParceirosRoute: typeof ParceirosRoute
  SitesTemplateSlugRoute: typeof SitesTemplateSlugRouteWithChildren
  SolucoesProductSlugRoute: typeof SolucoesProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DiagnosticoIndexRoute: typeof DiagnosticoIndexRoute
  MediaIndoorIndexRoute: typeof MediaIndoorIndexRoute
  MembrosIndexRoute: typeof MembrosIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  SitesAprovacaoTokenRoute: typeof SitesAprovacaoTokenRoute
  AdminSitesIndexRoute: typeof AdminSitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/': {
      id: '/diagnostico/'
      path: '/diagnostico'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof DiagnosticoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-indoor/': {
      id: '/media-indoor/'
      path: '/media-indoor'
      fullPath: '/media-indoor/'
      preLoaderRoute: typeof MediaIndoorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/': {
      id: '/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof MembrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$templateSlug': {
      id: '/sites/$templateSlug'
      path: '/sites/$templateSlug'
      fullPath: '/sites/$templateSlug'
      preLoaderRoute: typeof SitesTemplateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$productSlug': {
      id: '/solucoes/$productSlug'
      path: '/solucoes/$productSlug'
      fullPath: '/solucoes/$productSlug'
      preLoaderRoute: typeof SolucoesProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites/': {
      id: '/admin/sites/'
      path: '/admin/sites'
      fullPath: '/admin/sites/'
      preLoaderRoute: typeof AdminSitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/sites/': {
      id: '/cliente/sites/'
      path: '/sites'
      fullPath: '/cliente/sites/'
      preLoaderRoute: typeof ClienteSitesIndexRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/sites/$templateSlug/pedido': {
      id: '/sites/$templateSlug/pedido'
      path: '/pedido'
      fullPath: '/sites/$templateSlug/pedido'
      preLoaderRoute: typeof SitesTemplateSlugPedidoRouteImport
      parentRoute: typeof SitesTemplateSlugRoute
    }
    '/sites/aprovacao/$token': {
      id: '/sites/aprovacao/$token'
      path: '/sites/aprovacao/$token'
      fullPath: '/sites/aprovacao/$token'
      preLoaderRoute: typeof SitesAprovacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/sites/pagamento/$orderId': {
      id: '/cliente/sites/pagamento/$orderId'
      path: '/sites/pagamento/$orderId'
      fullPath: '/cliente/sites/pagamento/$orderId'
      preLoaderRoute: typeof ClienteSitesPagamentoOrderIdRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
  }
}

interface ClienteRouteRouteChildren {
  ClienteSitesIndexRoute: typeof ClienteSitesIndexRoute
  ClienteSitesPagamentoOrderIdRoute: typeof ClienteSitesPagamentoOrderIdRoute
}

const ClienteRouteRouteChildren: ClienteRouteRouteChildren = {
  ClienteSitesIndexRoute: ClienteSitesIndexRoute,
  ClienteSitesPagamentoOrderIdRoute: ClienteSitesPagamentoOrderIdRoute,
}

const ClienteRouteRouteWithChildren = ClienteRouteRoute._addFileChildren(
  ClienteRouteRouteChildren,
)

interface SitesTemplateSlugRouteChildren {
  SitesTemplateSlugPedidoRoute: typeof SitesTemplateSlugPedidoRoute
}

const SitesTemplateSlugRouteChildren: SitesTemplateSlugRouteChildren = {
  SitesTemplateSlugPedidoRoute: SitesTemplateSlugPedidoRoute,
}

const SitesTemplateSlugRouteWithChildren =
  SitesTemplateSlugRoute._addFileChildren(SitesTemplateSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRouteRoute: ClienteRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ParceirosRoute: ParceirosRoute,
  SitesTemplateSlugRoute: SitesTemplateSlugRouteWithChildren,
  SolucoesProductSlugRoute: SolucoesProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DiagnosticoIndexRoute: DiagnosticoIndexRoute,
  MediaIndoorIndexRoute: MediaIndoorIndexRoute,
  MembrosIndexRoute: MembrosIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  SitesAprovacaoTokenRoute: SitesAprovacaoTokenRoute,
  AdminSitesIndexRoute: AdminSitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
